# 3 containers in our service
# db is the mongo db database
# dbinit just initializes our database
# web is the main web app container which actually hosts the service
version: '3'
services:
 db:
  image: subs-mongo
  ports: 
   - "27017:27017"
 dbinit:
  image: subs-mongo-init
  depends_on:
    - "db"
 web:
  image: subs-wildfly
  ports: 
   - "8081:8080"
  stdin_open: true
  tty: true

  


