swagger: '2.0'
info:
  version: 1.0.0
  title: Subscription Service
  description: |
    Basic read operations to support subscriptions
host: 'localhost:8091'
basePath: /subscription
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /:
    get:
      summary: list subscriptions
      description: returns a list of subscriptions
      responses:
        '200':
          description: OK
          schema:
            title: Subscriptions
            type: array
            items:
              $ref: '#/definitions/Subscription'
  '/{subscriptionId}':
    get:
      summary: gets a subscription
      description: returns a subscription matching the supplied id
      parameters:
        - name: subscriptionId
          in: path
          type: string
          description: ID of the subscription
          required: true
      responses:
        '200':
          description: Sends the subscription details
        '400':
          description: The subscription id does not exist
definitions:
  Subscription:
    required:
      - id
      - name
      - description
      - price
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      description:
        type: string
        format: date
      price:
        type: number
        format: double