/**
 * Simple Inventory API
 * This is a simple API
 *
 * OpenAPI spec version: 1.0.0
 * Contact: you@your-company.com
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

import * as querystring from "querystring";
import * as url from "url";

import * as isomorphicFetch from "isomorphic-fetch";
import * as assign from "core-js/library/fn/object/assign";

interface Dictionary<T> { [index: string]: T; }
export interface FetchAPI { (url: string, init?: any): Promise<any>; }

const BASE_PATH = "https://virtserver.swaggerhub.com/MikeWay/SimplePurchase/1.0.0".replace(/\/+$/, '');

export interface FetchArgs {
    url: string;
    options: any; 
}

export class BaseAPI {
    basePath: string;
    fetch: FetchAPI;

    constructor(fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) {
        this.basePath = basePath;
        this.fetch = fetch;
    }
}



/**
 * DevelopersApi - fetch parameter creator
 */
export const DevelopersApiFetchParamCreactor = {
    /** 
     * Returns the number of days to get an item into stock
     * By passing in the itemId it will return the number of days to fulfill the stock 
     * @param itemId pass an optional search string for looking up inventory
     */
    searchInventory(params: {  itemId: string; }): FetchArgs {
        // verify required parameter "itemId" is set
        if (params["itemId"] == null) {
            throw new Error("Missing required parameter itemId when calling searchInventory");
        }
        const baseUrl = `/leadTime/{itemId}`
            .replace(`{${"itemId"}}`, `${ params.itemId }`);
        let urlObj = url.parse(baseUrl, true);
        let fetchOptions: RequestInit = { method: "GET" };

        let contentTypeHeader: Dictionary<string>;
        if (contentTypeHeader) {
            fetchOptions.headers = contentTypeHeader;
        }
        return {
            url: url.format(urlObj),
            options: fetchOptions,
        };
    },
}

/**
 * DevelopersApi - functional programming interface
 */
export const DevelopersApiFp = {
    /** 
     * Returns the number of days to get an item into stock
     * By passing in the itemId it will return the number of days to fulfill the stock 
     * @param itemId pass an optional search string for looking up inventory
     */
    searchInventory(params: { itemId: string;  }): (fetch: FetchAPI, basePath?: string) => Promise<number> {
        const fetchArgs = DevelopersApiFetchParamCreactor.searchInventory(params);
        return (fetch: FetchAPI = isomorphicFetch, basePath: string = BASE_PATH) => {
            return fetch(basePath + fetchArgs.url, fetchArgs.options).then((response) => {
                if (response.status >= 200 && response.status < 300) {
                    return response.json();
                } else {
                    throw response;
                }
            });
        };
    },
};

/**
 * DevelopersApi - object-oriented interface
 */
export class DevelopersApi extends BaseAPI {
    /** 
     * Returns the number of days to get an item into stock
     * By passing in the itemId it will return the number of days to fulfill the stock 
     * @param itemId pass an optional search string for looking up inventory
     */
    searchInventory(params: {  itemId: string; }) {
        return DevelopersApiFp.searchInventory(params)(this.fetch, this.basePath);
    }
};

/**
 * DevelopersApi - factory interface
 */
export const DevelopersApiFactory = function (fetch?: FetchAPI, basePath?: string) {
    return {
        /** 
         * Returns the number of days to get an item into stock
         * By passing in the itemId it will return the number of days to fulfill the stock 
         * @param itemId pass an optional search string for looking up inventory
         */
        searchInventory(params: {  itemId: string; }) {
            return DevelopersApiFp.searchInventory(params)(fetch, basePath);
        },
    }
};

