---
swagger: "2.0"
info:
  description: "Basic read operations to support subscriptions\n"
  version: "1.0.0"
  title: "Subscription Service"
host: "localhost:8091"
basePath: "/subscription"
schemes:
- "http"
- "https"
consumes:
- "application/json"
- "text/xml"
produces:
- "application/json"
- "text/html"
paths:
  /:
    get:
      summary: "list subscriptions"
      description: "returns a list of subscriptions"
      operationId: "rootGET"
      consumes:
      - "application/json"
      - "text/xml"
      produces:
      - "application/json"
      - "text/html"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            title: "Subscriptions"
            items:
              $ref: "#/definitions/inline_response_200"
      x-swagger-router-controller: "Default"
  /{subscriptionId}:
    get:
      summary: "gets a subscription"
      description: "returns a subscription matching the supplied id"
      operationId: "subscriptionIdGET"
      consumes:
      - "application/json"
      - "text/xml"
      produces:
      - "application/json"
      - "text/html"
      parameters:
      - name: "subscriptionId"
        in: "path"
        description: "ID of the subscription"
        required: true
        type: "string"
      responses:
        200:
          description: "Sends the subscription details"
        400:
          description: "The subscription id does not exist"
      x-swagger-router-controller: "Default"
definitions:
  Subscription:
    type: "object"
    required:
    - "description"
    - "id"
    - "name"
    - "price"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
        format: "date"
      price:
        type: "number"
        format: "double"
  inline_response_200:
    required:
    - "description"
    - "id"
    - "name"
    - "price"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      description:
        type: "string"
        format: "date"
      price:
        type: "number"
        format: "double"
