swagger: '2.0'
info:
  version: 1.0.0
  title: Member Service
  description: |
    Basic read operations to support members
host: 'localhost:8090'
basePath: /member
schemes:
  - http
  - https
consumes:
  - application/json
  - text/xml
produces:
  - application/json
  - text/html
paths:
  /:
    get:
      summary: list members
      description: returns a list of members
      responses:
        '200':
          description: OK
          schema:
            title: Members
            type: array
            items:
              $ref: '#/definitions/Member'
  '/{memberId}':
    get:
      summary: get a member
      description: returns details of a member matching the specified id
      parameters:
        - name: memberId
          in: path
          type: string
          description: ID of the member
          required: true
      responses:
        '200':
          description: Sends the member details
definitions:
  Member:
    required:
      - id  
      - name
      - address1
      - address2
      - email
    type: object
    properties:
      id:
        type: integer
        format: int64
      name:
        type: string
      dob:
        type: string
        format: date
      address1:
        type: string
      address2:
        type: string
      email:
        type: string
