FROM node:latest
ADD SimpleMembers /SimpleMembers/
ADD SimplePurchaseHistory /SimplePurchaseHistory/
ADD SimpleSubscription /SimpleSubscription/
ADD start-services.sh /
EXPOSE 8092 8090 8091
CMD ./start-services.sh
#CMD /bin/bash


