FROM node:latest
ADD SimpleInventory /SimpleInventory/
ADD SimpleProducts /SimpleProducts/
ADD SimplePurchase /SimplePurchase/
ADD start-services.sh /
EXPOSE 8092 8090 8091
CMD ./start-services.sh
#CMD /bin/bash


