---
swagger: "2.0"
info:
  description: "Basic read operations to support members\n"
  version: "1.0.0"
  title: "Member Service"
host: "localhost:8090"
basePath: "/member"
schemes:
- "http"
- "https"
consumes:
- "application/json"
- "text/xml"
produces:
- "application/json"
- "text/html"
paths:
  /:
    get:
      summary: "list members"
      description: "returns a list of members"
      operationId: "rootGET"
      consumes:
      - "application/json"
      - "text/xml"
      produces:
      - "application/json"
      - "text/html"
      parameters: []
      responses:
        200:
          description: "OK"
          schema:
            type: "array"
            title: "Members"
            items:
              $ref: "#/definitions/inline_response_200"
      x-swagger-router-controller: "Default"
  /{memberId}:
    get:
      summary: "get a member"
      description: "returns details of a member matching the specified id"
      operationId: "memberIdGET"
      consumes:
      - "application/json"
      - "text/xml"
      produces:
      - "application/json"
      - "text/html"
      parameters:
      - name: "memberId"
        in: "path"
        description: "ID of the member"
        required: true
        type: "string"
      responses:
        200:
          description: "Sends the member details"
          schema:
            $ref: "#/definitions/inline_response_200"
      x-swagger-router-controller: "Default"
definitions:
  Member:
    type: "object"
    required:
    - "address1"
    - "address2"
    - "email"
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      dob:
        type: "string"
        format: "date"
      address1:
        type: "string"
      address2:
        type: "string"
      email:
        type: "string"
  inline_response_200:
    required:
    - "address1"
    - "address2"
    - "email"
    - "id"
    - "name"
    properties:
      id:
        type: "integer"
        format: "int64"
      name:
        type: "string"
      dob:
        type: "string"
        format: "date"
      address1:
        type: "string"
      address2:
        type: "string"
      email:
        type: "string"
