swagger: '2.0'
info:
  description: Aggregated catalog data
  version: 1.0.0
  title: Simple Catalog API
  # put the contact info for your development or API team
  contact:
    email: you@your-company.com

  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html

# all paths will be relative to the basePath specified
# basePath: /v1

# tags are used for organizing operations
tags:
- name: admins
  description: Secured Admin-only calls
- name: developers
  description: Operations available to regular developers
schemes:
- https
paths:
  /product/{productId}:
    get:
      summary: searches inventory
      operationId: getPordocutById
      description: |
        By passing in the appropriate options, you can search for
        available inventory in the system
      produces:
      - application/json
      parameters:
      - in: path
        name: productId
        description: pass an optional search string for looking up inventory
        required: true
        type: string
      responses:
        200:
          description: search results matching criteria
          schema:
            type: array
            items:
              $ref: '#/definitions/Product'
        400:
          description: bad input parameter
definitions:
  Product:
    type: object
    required:
    - id
    - name
    - description
    - stockCount
    - leadTime
    properties:
      id:
        type: string
        format: uuid
        example: d290f1ee-6c54-4b01-90e6-d701748f0851
      name:
        type: string
        example: Widget Adapter
      description:
        type: string
      stockCount:
        type: number
      leadTime:
        type: number
        

# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
basePath: /MikeWay/Catalog/1.0.0